### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by filwie** [openrca/orca#60]
Hey Guys,
I created a logo prototype. Let me know what you think and we can discuss what to change or come up with something completely different that I can try to draw :)

I've heard @bzurkowski likes smiling animals with actual eyes, so this iteration combines both into below result (forgive me for png - svg is not supported here):

<img width="2439" alt="OpenRCA" src="https://user-images.githubusercontent.com/46937539/79915116-adef8280-8426-11ea-912c-3814a3ecad25.png">

<img width="250" alt="waves and stuff" src="https://user-images.githubusercontent.com/46937539/79915200-d37c8c00-8426-11ea-825d-268dc0dd1dad.png">

I welcome any feedback!

Cheers

**Comment by filwie** [comment]
And here it is with some background:
<img width="250" alt="orcabg" src="https://user-images.githubusercontent.com/46937539/79916781-949c0580-8429-11ea-800a-1b4823ca75cd.png">

**Comment by bzurkowski** [comment]
@filwie That's right. CNCF landscape is full of smiling animals and other strange creatures. Take project [Argo](https://argoproj.github.io/) as an example - it's very positive 😄Only [Jaeger](https://www.jaegertracing.io/)'s gopher and [Ambassador](https://www.getambassador.io/)'s penguin are an exception to the rule. They are just pure evil...

Thank you so much for the first draft. I really like the logo. I'm excited and can't wait to see the next versions. It's already a way better than the previous logo so I replaced it to catch the general look-and-feel. Unfortunately, the orca smiles only when I turn off the lights 💡

Light on 🌞 :
<img width="295" alt="Screenshot 2020-04-22 at 10 30 41" src="https://user-images.githubusercontent.com/6787563/79960081-4157a080-8485-11ea-9e1c-d909f57dbc75.png">
Light off 🌙 :
<img width="288" alt="Screenshot 2020-04-22 at 10 30 52" src="https://user-images.githubusercontent.com/6787563/79960094-44eb2780-8485-11ea-9f39-115a476996f2.png">

I don't really know if this is good or bad 😄Should we do something about it?

If it's not much of a problem, I would love to see alternative options, e.g. orca with a tail-fin or slim orca - whatever you decide to modify. Just to have a different perspective and more trouble in choosing the best option.

Also, if you haven't already, you can take a look at the CNCF [zoo](https://landscape.cncf.io/) for more inspiration.

Thanks!

**Comment by k-jano** [comment]
@filwie 

I have to admit that it's a great proposition! 👍  Looks very neat and fits in with current trends 📈 If possible, I look forward to the next options!

**Comment by bzurkowski** [comment]
Amazing logo added in #79!
